### ISSUE TITLE
Which cuda version is required for this code. i am tired of tensorflow 1.5 and cuda 9. its having the following error

### ISSUE THREAD

**Issue by qaazii** [kshmelkov/incremental_detectors#8]
failedpreconditionerror (see above for traceback): attempting to use uninitialized value resnet_v1_50/block3/unit_2/bottleneck_v1/conv2/batchnorm/moving_variance

**Comment by kshmelkov** [comment]
You should use CUDA version compatible with TF 1.5, it shouldn't matter. This error has nothing to do with CUDA, it looks like something went wrong with resnet checkpoint restoration.

**Comment by qaazii** [comment]
Most of the solution shows that there is there should sess =  tf.session() after tf.global_variable_initilaizer(). I tried that still not working.

The model is training but when evaluation it araise this error

**Comment by qaazii** [comment]
For your information i get the folowing error after evaluation 


[INFO]: step 310, loss = 1.88, acc = 0.78 bg = 0.97 (8.3 ex/sec; 0.242 sec/batch)
[INFO]: step 320, loss = 1.42, acc = 0.80 bg = 0.85 (8.6 ex/sec; 0.233 sec/batch)
[INFO]: step 330, loss = 1.74, acc = 0.91 bg = 0.69 (8.6 ex/sec; 0.232 sec/batch)
[INFO]: step 340, loss = 1.51, acc = 0.90 bg = 0.76 (3.7 ex/sec; 0.534 sec/batch)
[INFO]: step 350, loss = 1.50, acc = 0.91 bg = 0.69 (4.2 ex/sec; 0.480 sec/batch)
[INFO]: step 360, loss = 2.05, acc = 0.73 bg = 0.98 (8.4 ex/sec; 0.237 sec/batch)
[INFO]: step 370, loss = 1.86, acc = 0.75 bg = 1.00 (8.4 ex/sec; 0.238 sec/batch)
[INFO]: step 380, loss = 1.61, acc = 0.86 bg = 0.88 (8.6 ex/sec; 0.233 sec/batch)
[INFO]: step 390, loss = 1.70, acc = 0.78 bg = 0.94 (8.5 ex/sec; 0.235 sec/batch)
[INFO]: step 400, loss = 1.58, acc = 0.89 bg = 0.78 (8.1 ex/sec; 0.248 sec/batch)
2020-04-29 15:27:49.851022: I C:\users\nwani\_bazel_nwani\ujdkfsks\execroot\org_tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1471] Adding visible gpu devices: 0
2020-04-29 15:27:49.855916: I C:\users\nwani\_bazel_nwani\ujdkfsks\execroot\org_tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:952] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-04-29 15:27:49.861104: I C:\users\nwani\_bazel_nwani\ujdkfsks\execroot\org_tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:958]      0
2020-04-29 15:27:49.864344: I C:\users\nwani\_bazel_nwani\ujdkfsks\execroot\org_tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:971] 0:   N
2020-04-29 15:27:49.868161: I C:\users\nwani\_bazel_nwani\ujdkfsks\execroot\org_tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8781 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
[INFO]: Completely new network
[INFO]: Checkpoint 40k
Traceback (most recent call last):                                            |
  File "C:\Users\power703\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1322, in _do_call
    return fn(*args)
  File "C:\Users\power703\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "C:\Users\power703\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value fc8/weights
         [[Node: fc8/weights/read = Identity[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](fc8/weights)]]
         [[Node: strided_slice_2/_13 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1086_strided_slice_2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "frcnn.py", line 441, in <module>
    tf.app.run()
  File "C:\Users\power703\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "frcnn.py", line 423, in main
    eval_network(sess)
  File "frcnn.py", line 346, in eval_network
    results = Evaluation(net, loader, ckpt_num, args.conf_thresh, args.nms_thresh).evaluate_network(args.eval_first_n)
  File "C:\Users\power703\Desktop\incremental_detectors\evaluation.py", line 48, in evaluate_network
    self.process_image(filenames[i], i)
  File "C:\Users\power703\Desktop\incremental_detectors\evaluation.py", line 102, in process_image
    nms_thresh=self.nms_thresh)
  File "C:\Users\power703\Desktop\incremental_detectors\network.py", line 172, in detect
    softmax, sigmoid, bboxes, logits = self._forward_pass(image, proposals)
  File "C:\Users\power703\Desktop\incremental_detectors\network.py", line 167, in _forward_pass
    self.rois_ph: rois})
  File "C:\Users\power703\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 900, in run
    run_metadata_ptr)
  File "C:\Users\power703\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\power703\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1316, in _do_run
    run_metadata)
  File "C:\Users\power703\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value fc8/weights
         [[Node: fc8/weights/read = Identity[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](fc8/weights)]]
         [[Node: strided_slice_2/_13 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1086_strided_slice_2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'fc8/weights/read', defined at:
  File "frcnn.py", line 441, in <module>
    tf.app.run()
  File "C:\Users\power703\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "frcnn.py", line 423, in main
    eval_network(sess)
  File "frcnn.py", line 324, in eval_network
    net = Network(num_classes=args.num_classes+args.extend, distillation=False)
  File "C:\Users\power703\Desktop\incremental_detectors\network.py", line 34, in __init__
    self.inference()
  File "C:\Users\power703\Desktop\incremental_detectors\network.py", line 148, in inference
    weights_initializer=tf.truncated_normal_initializer(stddev=0.01))
  File "C:\Users\power703\Anaconda3\lib\site-packages\tensorflow\contrib\framework\python\ops\arg_scope.py", line 183, in func_with_args
    return func(*args, **current_args)
  File "C:\Users\power703\Anaconda3\lib\site-packages\tensorflow\contrib\layers\python\layers\layers.py", line 1849, in fully_connected
    outputs = layer.apply(inputs)
  File "C:\Users\power703\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 774, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "C:\Users\power703\Anaconda3\lib\site-packages\tensorflow\python\layers\base.py", line 329, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "C:\Users\power703\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 696, in __call__
    self.build(input_shapes)
  File "C:\Users\power703\Anaconda3\lib\site-packages\tensorflow\python\keras\layers\core.py", line 891, in build
    trainable=True)
  File "C:\Users\power703\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 460, in add_variable
    return self.add_weight(*args, **kwargs)
  File "C:\Users\power703\Anaconda3\lib\site-packages\tensorflow\python\layers\base.py", line 243, in add_weight
    getter=vs.get_variable)
  File "C:\Users\power703\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 534, in add_weight
    use_resource=use_resource)
  File "C:\Users\power703\Anaconda3\lib\site-packages\tensorflow\python\training\checkpointable\base.py", line 497, in _add_variable_with_custom_getter
    **kwargs_for_getter)
  File "C:\Users\power703\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 1328, in get_variable
    constraint=constraint)
  File "C:\Users\power703\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 1090, in get_variable
    constraint=constraint)
  File "C:\Users\power703\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 427, in get_variable
    return custom_getter(**custom_getter_kwargs)
  File "C:\Users\power703\Anaconda3\lib\site-packages\tensorflow\contrib\layers\python\layers\layers.py", line 1744, in layer_variable_getter
    return _model_variable_getter(getter, *args, **kwargs)
  File "C:\Users\power703\Anaconda3\lib\site-packages\tensorflow\contrib\layers\python\layers\layers.py", line 1735, in _model_variable_getter
    use_resource=use_resource)
  File "C:\Users\power703\Anaconda3\lib\site-packages\tensorflow\contrib\framework\python\ops\arg_scope.py", line 183, in func_with_args
    return func(*args, **current_args)
  File "C:\Users\power703\Anaconda3\lib\site-packages\tensorflow\contrib\framework\python\ops\variables.py", line 297, in model_variable
    use_resource=use_resource)
  File "C:\Users\power703\Anaconda3\lib\site-packages\tensorflow\contrib\framework\python\ops\arg_scope.py", line 183, in func_with_args
    return func(*args, **current_args)
  File "C:\Users\power703\Anaconda3\lib\site-packages\tensorflow\contrib\framework\python\ops\variables.py", line 252, in variable
    use_resource=use_resource)
  File "C:\Users\power703\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 404, in _true_getter
    use_resource=use_resource, constraint=constraint)
  File "C:\Users\power703\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 796, in _get_single_variable
    use_resource=use_resource)
  File "C:\Users\power703\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 2234, in variable
    use_resource=use_resource)
  File "C:\Users\power703\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 2224, in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
  File "C:\Users\power703\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 2207, in default_variable_creator
    constraint=constraint)
  File "C:\Users\power703\Anaconda3\lib\site-packages\tensorflow\python\ops\variables.py", line 259, in __init__
    constraint=constraint)
  File "C:\Users\power703\Anaconda3\lib\site-packages\tensorflow\python\ops\variables.py", line 422, in _init_from_args
    self._snapshot = array_ops.identity(self._variable, name="read")
  File "C:\Users\power703\Anaconda3\lib\site-packages\tensorflow\python\ops\array_ops.py", line 79, in identity
    return gen_array_ops.identity(input, name=name)
  File "C:\Users\power703\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 3262, in identity
    "Identity", input=input, name=name)
  File "C:\Users\power703\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\power703\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3414, in create_op
    op_def=op_def)
  File "C:\Users\power703\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1740, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

FailedPreconditionError (see above for traceback): Attempting to use uninitialized value fc8/weights
         [[Node: fc8/weights/read = Identity[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](fc8/weights)]]
         [[Node: strided_slice_2/_13 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1086_strided_slice_2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

**Comment by qaazii** [comment]
Also when i train for few epoch the events is saving, i think there is no weights saved. below is the picture of the folder where my checkpoints is supposed to be saved. 

[
![Capture](https://user-images.githubusercontent.com/13545904/80615736-a194a680-8a72-11ea-9657-1931bae78145.PNG)
](![image](https://user-images.githubusercontent.com/13545904/80615667-8d50a980-8a72-11ea-8c1b-9ab448b11862.png))

**Comment by qaazii** [comment]
Okay I solved this problem. It was because i trained for only 400 epoch so it didnt store the checkpoints. after training for 2000 epoch it started evaluation but the system is hanged after restoring checkpoins. as given in the following figure
![image](https://user-images.githubusercontent.com/13545904/80624191-ebcf5500-8a7d-11ea-8e85-211036ce7b75.png)
